"""empty message

Revision ID: fe637e0fc547
Revises: 0a48baee3899
Create Date: 2023-06-14 15:11:49.289681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe637e0fc547'
down_revision = '0a48baee3899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    # Set existing rows in 'jobs' table to have 'favorite' value as False
    op.execute("UPDATE jobs SET favorite = 'False'")

    # Modify the column to be non-nullable
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('favorite', existing_type=sa.Boolean(), nullable=False, server_default='False')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###
